services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidosdatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
      - ./db.cnf:/etc/mysql/conf.d/db.cnf  # Montar el archivo de configuración
    networks:
      - mydb-network
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - mydb-network

networks:
  mydb-network:

volumes:
  mysql_data:
